# Generated by Django 4.2.16 on 2026-10-06 03:50

import apps.servers.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('api_url', models.URLField(max_length=300)),
                ('http_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], default='POST', max_length=4)),
                ('api_key', apps.servers.models.EncryptedField(blank=True, default='')),
                ('secret_key', apps.servers.models.EncryptedField(blank=True, default='')),
                ('sender_id', models.CharField(blank=True, max_length=30)),
                ('params_template', models.JSONField(default=dict)),
                ('success_keyword', models.CharField(blank=True, max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMS Gateway',
                'db_table': 'sms_gateways',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('event', models.CharField(choices=[('custom', 'Custom'), ('due_reminder', 'Due Reminder'), ('expiry_reminder', 'Expiry Reminder'), ('payment_received', 'Payment Received'), ('welcome', 'Welcome')], default='custom', max_length=20)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMS Template',
                'db_table': 'sms_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SMSGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('extra_numbers', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clients', models.ManyToManyField(blank=True, related_name='sms_groups', to='clients.client')),
            ],
            options={
                'verbose_name': 'SMS Group',
                'db_table': 'sms_groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(db_index=True, max_length=20)),
                ('message', models.TextField()),
                ('sms_count', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', max_length=8)),
                ('response', models.TextField(blank=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_messages', to='clients.client')),
                ('gateway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='sms.smsgateway')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_sent', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='sms.smstemplate')),
            ],
            options={
                'verbose_name': 'SMS Message',
                'db_table': 'sms_messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='sms_message_status_058598_idx')],
            },
        ),
    ]
