# Generated by Django 4.2.16 on 2026-10-06 03:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='যেমন: 1001, 2001, 4001', max_length=20, unique=True, verbose_name='Account Code')),
                ('name', models.CharField(max_length=150, verbose_name='Account Name')),
                ('description', models.TextField(blank=True)),
                ('is_group', models.BooleanField(default=False, help_text='Group account-এ সরাসরি transaction হয় না', verbose_name='Group Account?')),
                ('is_system', models.BooleanField(default=False, help_text='System account delete করা যাবে না', verbose_name='System Account?')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Opening Balance (BDT)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Account',
                'db_table': 'acc_accounts',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_month', models.DateField(help_text='মাসের শুরুর তারিখ (YYYY-MM-01)')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_debit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_credit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Account Balance',
                'db_table': 'acc_account_balances',
                'ordering': ['-period_month', 'account__code'],
            },
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('nature', models.CharField(choices=[('debit', 'Debit (বামদিকে বাড়ে)'), ('credit', 'Credit (ডানদিকে বাড়ে)')], help_text='Debit nature = Asset/Expense; Credit = Liability/Equity/Income', max_length=6)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Account Type',
                'db_table': 'acc_account_types',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_no', models.CharField(max_length=30, unique=True, verbose_name='Journal Entry No.')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('entry_type', models.CharField(choices=[('manual', 'Manual Journal'), ('income', 'Income'), ('expense', 'Expense'), ('payment', 'Payment Collection'), ('purchase', 'Purchase'), ('salary', 'Salary Payment'), ('transfer', 'Bank Transfer'), ('opening', 'Opening Entry'), ('adjustment', 'Adjustment')], default='manual', max_length=12)),
                ('description', models.TextField(verbose_name='Narration / Description')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Reference No.')),
                ('reference_model', models.CharField(blank=True, help_text='যেমন: billing, payment, payslip', max_length=50)),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_posted', models.BooleanField(default=False, help_text='Posted হলে edit/delete করা যাবে না', verbose_name='Posted?')),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'db_table': 'acc_journal_entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('debit', 'Debit (ডেবিট)'), ('credit', 'Credit (ক্রেডিট)')], max_length=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('description', models.CharField(blank=True, max_length=200)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_lines', to='accounting.account')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry')),
            ],
            options={
                'verbose_name': 'Transaction Line',
                'db_table': 'acc_transaction_lines',
            },
        ),
    ]
