# Generated by Django 4.2.16 on 2026-10-06 03:50

import apps.servers.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('sslcommerz', 'SSL Commerz'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('other', 'Other')], max_length=15, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('store_id', models.CharField(blank=True, max_length=150)),
                ('store_password', apps.servers.models.EncryptedField(blank=True, default='')),
                ('api_key', apps.servers.models.EncryptedField(blank=True, default='')),
                ('api_secret', apps.servers.models.EncryptedField(blank=True, default='')),
                ('is_sandbox', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
                ('extra_config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Gateway',
                'db_table': 'system_payment_gateways',
                'ordering': ['provider'],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grace_days', models.PositiveSmallIntegerField(default=0)),
                ('auto_disable_expired', models.BooleanField(default=True)),
                ('auto_generate_bills', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=False)),
                ('expiry_reminder_days', models.PositiveSmallIntegerField(default=3)),
                ('send_payment_sms', models.BooleanField(default=True)),
                ('date_format', models.CharField(default='DD/MM/YYYY', max_length=20)),
                ('timezone', models.CharField(default='Asia/Dhaka', max_length=50)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Setting',
                'db_table': 'system_settings',
            },
        ),
        migrations.CreateModel(
            name='PaymentProcessingFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[('percent', 'Percentage'), ('fixed', 'Fixed Amount')], default='percent', max_length=8)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('born_by', models.CharField(choices=[('client', 'Client pays'), ('company', 'Company pays')], default='client', max_length=8)),
                ('min_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('max_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='system_config.paymentgateway')),
            ],
            options={
                'verbose_name': 'Payment Processing Fee',
                'db_table': 'system_payment_processing_fees',
            },
        ),
        migrations.CreateModel(
            name='InvoiceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prefix', models.CharField(default='INV', max_length=10)),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('paper_size', models.CharField(choices=[('a4', 'A4'), ('a5', 'A5'), ('pos', 'POS (80mm)')], default='a4', max_length=5)),
                ('show_logo', models.BooleanField(default=True)),
                ('footer_note', models.CharField(blank=True, max_length=255)),
                ('terms', models.TextField(blank=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invoice Setting',
                'db_table': 'system_invoice_settings',
            },
        ),
        migrations.CreateModel(
            name='EmailSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.CharField(blank=True, max_length=150)),
                ('port', models.PositiveIntegerField(default=587)),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('password', apps.servers.models.EncryptedField(blank=True, default='')),
                ('from_email', models.EmailField(blank=True, max_length=254)),
                ('from_name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Setting',
                'db_table': 'system_email_settings',
            },
        ),
        migrations.CreateModel(
            name='CompanySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='ISP Company', max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('currency', models.CharField(default='BDT', max_length=10)),
                ('license_no', models.CharField(blank=True, max_length=100)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Setting',
                'db_table': 'system_company_settings',
            },
        ),
    ]
