# Generated by Django 4.2.16 on 2026-10-06 05:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
        ('billing', '0001_initial'),
        ('mac_reseller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MACResellerPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Package Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('bandwidth_down', models.PositiveIntegerField(verbose_name='Download Speed (Mbps)')),
                ('bandwidth_up', models.PositiveIntegerField(verbose_name='Upload Speed (Mbps)')),
                ('duration_days', models.PositiveIntegerField(default=30, verbose_name='Duration (Days)')),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Retail Price (৳)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mac_packages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MAC Reseller Package',
                'db_table': 'mac_reseller_packages',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='macreseller',
            options={'ordering': ['name'], 'verbose_name': 'MAC Reseller'},
        ),
        migrations.RemoveField(
            model_name='macreseller',
            name='is_active',
        ),
        migrations.AddField(
            model_name='macreseller',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Account Balance (৳)'),
        ),
        migrations.AddField(
            model_name='macreseller',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mac_resellers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='macreseller',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Address'),
        ),
        migrations.AddField(
            model_name='macreseller',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], db_index=True, default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='macreseller',
            name='contact',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone/Contact'),
        ),
        migrations.AlterField(
            model_name='macreseller',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Reseller Name'),
        ),
        migrations.AlterModelTable(
            name='macreseller',
            table='mac_resellers',
        ),
        migrations.CreateModel(
            name='MACResellerNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Notice Title')),
                ('content', models.TextField(verbose_name='Notice Content')),
                ('notice_type', models.CharField(choices=[('general', 'General Notice'), ('billing', 'Billing Notice'), ('system', 'System Update'), ('urgent', 'Urgent'), ('promotion', 'Promotion')], default='general', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('publish_at', models.DateTimeField(verbose_name='Publish At')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='Expire At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notices', to=settings.AUTH_USER_MODEL)),
                ('target_resellers', models.ManyToManyField(blank=True, related_name='notices', to='mac_reseller.macreseller', verbose_name='Target Resellers (empty = all)')),
            ],
            options={
                'verbose_name': 'MAC Reseller Notice',
                'db_table': 'mac_reseller_notices',
                'ordering': ['-publish_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientPGWPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Payment Amount (৳)')),
                ('gateway', models.CharField(choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('sslcommerz', 'SSL Commerz'), ('upay', 'Upay'), ('dmoney', 'Dmoney'), ('other', 'Other')], default='bkash', max_length=15, verbose_name='Payment Gateway')),
                ('pgw_transaction_id', models.CharField(blank=True, max_length=200, verbose_name='PGW Transaction ID')),
                ('order_id', models.CharField(max_length=100, unique=True, verbose_name='Order ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=10)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('note', models.TextField(blank=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pgw_payments', to='billing.billing', verbose_name='Related Billing')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pgw_payments', to='clients.client', verbose_name='Client')),
                ('reseller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_pgw_payments', to='mac_reseller.macreseller', verbose_name='Reseller')),
            ],
            options={
                'verbose_name': 'Client PGW Payment',
                'db_table': 'client_pgw_payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PGWTransactionSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_count', models.PositiveIntegerField(default=0, verbose_name='No. of Payments')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Payment Amount (৳)')),
                ('total_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Processing Fee (৳)')),
                ('net_settlement', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Net Settlement Amount (৳)')),
                ('settlement_date', models.DateField(verbose_name='Settlement Date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('partial', 'Partial')], db_index=True, default='pending', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payments', models.ManyToManyField(blank=True, related_name='settlements', to='mac_reseller.clientpgwpayment')),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='mac_reseller.macreseller', verbose_name='Reseller')),
                ('settled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pgw_settlements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PGW Transaction Settlement',
                'db_table': 'pgw_transaction_settlements',
                'ordering': ['-settlement_date'],
                'indexes': [models.Index(fields=['reseller', 'status'], name='pgw_transac_reselle_900423_idx'), models.Index(fields=['status', 'settlement_date'], name='pgw_transac_status_a12286_idx')],
            },
        ),
        migrations.CreateModel(
            name='MACResellerTariffConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reseller_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Reseller Buy Price (৳)')),
                ('max_retail_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Max Allowed Retail Price (৳)')),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(verbose_name='Effective From')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tariff_configs', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariff_configs', to='mac_reseller.macresellerpackage', verbose_name='Package')),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariff_configs', to='mac_reseller.macreseller', verbose_name='Reseller')),
            ],
            options={
                'verbose_name': 'Tariff Config',
                'db_table': 'mac_reseller_tariff_configs',
                'ordering': ['reseller', 'package'],
                'unique_together': {('reseller', 'package')},
            },
        ),
        migrations.CreateModel(
            name='MACResellerFunding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Funding Amount (৳)')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque'), ('online', 'Online')], default='cash', max_length=10)),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='Transaction ID / Ref')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10)),
                ('balance_before', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('funded_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_fundings', to=settings.AUTH_USER_MODEL)),
                ('funded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fundings', to=settings.AUTH_USER_MODEL)),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundings', to='mac_reseller.macreseller', verbose_name='Reseller')),
            ],
            options={
                'verbose_name': 'Reseller Funding',
                'db_table': 'mac_reseller_fundings',
                'ordering': ['-funded_at'],
                'indexes': [models.Index(fields=['reseller', 'status'], name='mac_reselle_reselle_820100_idx'), models.Index(fields=['status', 'funded_at'], name='mac_reselle_status_e8368d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='clientpgwpayment',
            index=models.Index(fields=['status', 'created_at'], name='client_pgw__status_1c482a_idx'),
        ),
        migrations.AddIndex(
            model_name='clientpgwpayment',
            index=models.Index(fields=['client', 'status'], name='client_pgw__client__d5d79b_idx'),
        ),
        migrations.AddIndex(
            model_name='clientpgwpayment',
            index=models.Index(fields=['reseller', 'status'], name='client_pgw__reselle_6be8d3_idx'),
        ),
    ]
