# Generated by Django 4.2.16 on 2026-10-06 03:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_month', models.DateField(help_text='বিলের মাস (YYYY-MM-01 format)')),
                ('bill_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payable_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('due_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('advance_used', models.DecimalField(decimal_places=2, default=0, help_text='Advance balance থেকে কত কেটেছে', max_digits=10)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid'), ('waived', 'Waived/Forgiven'), ('overdue', 'Overdue')], db_index=True, default='unpaid', max_length=10)),
                ('bill_date', models.DateField(help_text='যে তারিখে বিল generate হয়েছে')),
                ('due_date', models.DateField(help_text='পরিশোধের শেষ তারিখ (expiry_date)')),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billings', to='clients.client')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills_generated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Billing',
                'db_table': 'billings',
                'ordering': ['-bill_month', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('bank', 'Bank Transfer'), ('card', 'Card'), ('online', 'Online (SSL Commerz)'), ('advance', 'From Advance Balance'), ('waiver', 'Waiver/Forgiven')], default='cash', max_length=10)),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('billing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.billing')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='clients.client')),
                ('collected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_collected', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'db_table': 'payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'payment_date'], name='payments_client__2fa969_idx'), models.Index(fields=['method', 'payment_date'], name='payments_method_89ec98_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='billing',
            index=models.Index(fields=['status', 'bill_month'], name='billings_status_264c87_idx'),
        ),
        migrations.AddIndex(
            model_name='billing',
            index=models.Index(fields=['client', 'bill_month'], name='billings_client__412238_idx'),
        ),
        migrations.AddIndex(
            model_name='billing',
            index=models.Index(fields=['due_date', 'status'], name='billings_due_dat_3c7b75_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='billing',
            unique_together={('client', 'bill_month')},
        ),
    ]
