# Generated by Django 4.2.16 on 2026-10-06 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Income (BDT)')),
                ('bill_collection', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Bill Collection (BDT)')),
                ('connection_fee', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Connection Fee (BDT)')),
                ('other_income', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Other Income (BDT)')),
                ('total_expense', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Expense (BDT)')),
                ('opening_cash', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Opening Cash Balance (BDT)')),
                ('closing_cash', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Closing Cash Balance (BDT)')),
                ('net_profit_loss', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Net Profit / Loss (BDT)')),
                ('cash_in_hand', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bkash_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('nagad_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rocket_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bank_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=8)),
                ('note', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_accounts_closed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Account',
                'db_table': 'daily_accounts',
                'ordering': ['-date'],
            },
        ),
    ]
