# Generated by Django 4.2.16 on 2026-10-06 03:50

import apps.servers.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servers', '0001_initial'),
        ('configuration', '0001_initial'),
        ('mac_reseller', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('father_name', models.CharField(blank=True, max_length=150, verbose_name="Father's Name")),
                ('phone', models.CharField(db_index=True, max_length=20, validators=[utils.validators.validate_bd_phone], verbose_name='Phone Number')),
                ('alt_phone', models.CharField(blank=True, max_length=20, validators=[utils.validators.validate_bd_phone], verbose_name='Alternate Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
                ('nid', models.CharField(blank=True, max_length=20, validators=[utils.validators.validate_nid], verbose_name='NID Number')),
                ('house_name', models.CharField(blank=True, max_length=150, verbose_name='House/Building Name')),
                ('house_no', models.CharField(blank=True, max_length=30, verbose_name='House No.')),
                ('road_no', models.CharField(blank=True, max_length=50, verbose_name='Road/Street No.')),
                ('address', models.TextField(blank=True, verbose_name='Full Address')),
                ('map_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Map Latitude')),
                ('map_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Map Longitude')),
                ('package_no', models.CharField(blank=True, max_length=50, verbose_name='Package No/Code')),
                ('username', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='PPPoE Username')),
                ('password', apps.servers.models.EncryptedField(verbose_name='PPPoE Password (Encrypted)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, validators=[utils.validators.validate_ip_address])),
                ('mac_address', models.CharField(blank=True, max_length=20, validators=[utils.validators.validate_mac_address])),
                ('pppoe_profile', models.CharField(blank=True, max_length=100, verbose_name='PPPoE Profile Name')),
                ('bill_date', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Bill Day of Month (1-31)')),
                ('expiry_day', models.PositiveSmallIntegerField(default=30, verbose_name='Expiry Days After Bill Date')),
                ('billing_start_month', models.DateField(blank=True, null=True, verbose_name='Billing Start Month')),
                ('connection_date', models.DateField(default=django.utils.timezone.now, verbose_name='Connection Date')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Current Expiry Date')),
                ('monthly_bill', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monthly Bill (BDT)')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Discount (BDT)')),
                ('due_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Due Amount (BDT)')),
                ('advance_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Advance Balance (BDT)')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('disconnected', 'Disconnected'), ('left', 'Left/Cancelled')], db_index=True, default='active', max_length=15)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('partial', 'Partial'), ('overdue', 'Overdue')], default='unpaid', max_length=10)),
                ('is_renewed', models.BooleanField(default=False, verbose_name='Is Renewed This Month')),
                ('renewed_at', models.DateTimeField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='clients/photos/')),
                ('nid_photo', models.ImageField(blank=True, null=True, upload_to='clients/nid/', verbose_name='NID Photo')),
                ('reg_form_pic', models.ImageField(blank=True, null=True, upload_to='clients/reg_forms/', verbose_name='Registration Form Photo')),
                ('app_enabled', models.BooleanField(default=False, verbose_name='Mobile App Enabled')),
                ('app_password', models.CharField(blank=True, max_length=64, verbose_name='App Login Password')),
                ('app_last_seen', models.DateTimeField(blank=True, null=True, verbose_name='App Last Seen')),
                ('app_registered_on', models.DateTimeField(blank=True, null=True, verbose_name='App Registration Date')),
                ('device', models.CharField(blank=True, max_length=100, verbose_name='Device Type/Model')),
                ('optical_fiber', models.BooleanField(default=True, verbose_name='Optical Fiber Connection')),
                ('cable_meter', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Cable Length (meters)')),
                ('vendor', models.CharField(blank=True, max_length=100, verbose_name='Hardware Vendor')),
                ('serial_no', models.CharField(blank=True, max_length=64, verbose_name='ONU/ONT Serial Number')),
                ('fiber_code', models.CharField(blank=True, max_length=50, verbose_name='Fiber Code')),
                ('color_of_cord', models.CharField(blank=True, max_length=50, verbose_name='Color of Cord')),
                ('device_purchase_date', models.DateField(blank=True, null=True, verbose_name='Device Purchase Date')),
                ('remote_mgmt_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Remote Management IP')),
                ('remote_admin_user', models.CharField(blank=True, max_length=64, verbose_name='Remote Admin Username')),
                ('remote_admin_pass', apps.servers.models.EncryptedField(blank=True, verbose_name='Remote Admin Password (Encrypted)')),
                ('mac_reseller_exported', models.BooleanField(default=False, verbose_name='Exported to MAC Reseller')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='configuration.box')),
                ('client_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.clienttype')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_created', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.district', verbose_name='District')),
                ('mac_reseller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='mac_reseller.macreseller')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='configuration.package')),
                ('protocol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.protocoltype')),
                ('router', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='servers.mikrotikrouter')),
                ('subzone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='configuration.subzone')),
                ('thana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.upazila', verbose_name='Thana/Upazila')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='configuration.zone')),
            ],
            options={
                'verbose_name': 'Client',
                'db_table': 'clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('activated', 'Activated'), ('suspended', 'Suspended'), ('disconnected', 'Disconnected'), ('renewed', 'Renewed'), ('expired', 'Auto Expired'), ('left', 'Left/Cancelled')], max_length=20)),
                ('from_status', models.CharField(max_length=15)),
                ('to_status', models.CharField(max_length=15)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='clients.client')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Status Log',
                'db_table': 'client_status_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['status', 'expiry_date'], name='clients_status_0e3385_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['zone', 'status'], name='clients_zone_id_b99e2a_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['bill_date', 'status'], name='clients_bill_da_faea4f_idx'),
        ),
    ]
