# Generated by Django 4.2.16 on 2026-10-06 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Billing Status')),
                ('color_code', models.CharField(default='#000000', max_length=10, verbose_name='Color (Hex)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Billing Status',
                'db_table': 'config_billing_statuses',
            },
        ),
        migrations.CreateModel(
            name='ClientType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Client Type')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Client Type',
                'db_table': 'config_client_types',
            },
        ),
        migrations.CreateModel(
            name='ConnectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Connection Type')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Connection Type',
                'db_table': 'config_connection_types',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='District Name')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'District',
                'db_table': 'config_districts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProtocolType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Protocol Type')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Protocol Type',
                'db_table': 'config_protocol_types',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Zone Name')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zones_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zone',
                'db_table': 'config_zones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Sub Zone Name')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_zones', to='configuration.zone')),
            ],
            options={
                'verbose_name': 'Sub Zone',
                'db_table': 'config_sub_zones',
                'ordering': ['name'],
                'unique_together': {('zone', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Package Name')),
                ('package_type', models.CharField(choices=[('pppoe', 'PPPoE'), ('static', 'Static IP'), ('hotspot', 'Hotspot')], default='pppoe', max_length=20)),
                ('download_speed', models.CharField(max_length=20, verbose_name='Download Speed (Mbps)')),
                ('upload_speed', models.CharField(max_length=20, verbose_name='Upload Speed (Mbps)')),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monthly Price (BDT)')),
                ('description', models.TextField(blank=True)),
                ('mikrotik_profile', models.CharField(blank=True, max_length=100, verbose_name='Mikrotik Profile Name')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Package',
                'db_table': 'config_packages',
                'ordering': ['monthly_price'],
            },
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Box Name')),
                ('location', models.TextField(blank=True, verbose_name='Box Location')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sub_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='configuration.subzone')),
            ],
            options={
                'verbose_name': 'Box',
                'db_table': 'config_boxes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Upazila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Upazila/Thana Name')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upazilas', to='configuration.district')),
            ],
            options={
                'verbose_name': 'Upazila',
                'db_table': 'config_upazilas',
                'ordering': ['name'],
                'unique_together': {('district', 'name')},
            },
        ),
    ]
