# Generated by Django 4.2.16 on 2026-10-06 03:50

import apps.servers.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MikrotikRouter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Router Name')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Router IP Address')),
                ('api_port', models.PositiveIntegerField(default=8728, verbose_name='RouterOS API Port')),
                ('api_username', models.CharField(max_length=100, verbose_name='API Username')),
                ('api_password', apps.servers.models.EncryptedField(verbose_name='API Password (Encrypted)')),
                ('ssh_port', models.PositiveIntegerField(default=22, verbose_name='SSH Port')),
                ('ssh_username', models.CharField(blank=True, max_length=100, verbose_name='SSH Username')),
                ('ssh_password', apps.servers.models.EncryptedField(blank=True, verbose_name='SSH Password (Encrypted)')),
                ('nas_identifier', models.CharField(blank=True, max_length=64, verbose_name='NAS Identifier')),
                ('nas_secret', apps.servers.models.EncryptedField(blank=True, verbose_name='NAS Secret (Encrypted)')),
                ('nas_port', models.PositiveIntegerField(default=3799, verbose_name='NAS CoA Port')),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('last_checked', models.DateTimeField(blank=True, null=True, verbose_name='Last Status Check')),
                ('last_backup', models.DateTimeField(blank=True, null=True, verbose_name='Last Backup Time')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routers', to='configuration.zone')),
            ],
            options={
                'verbose_name': 'Mikrotik Router',
                'db_table': 'servers_mikrotik_routers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RadAcct',
            fields=[
                ('radacctid', models.BigAutoField(primary_key=True, serialize=False)),
                ('acctsessionid', models.CharField(max_length=64)),
                ('acctuniqueid', models.CharField(max_length=32, unique=True)),
                ('username', models.CharField(db_index=True, max_length=64)),
                ('realm', models.CharField(blank=True, max_length=64)),
                ('nasipaddress', models.GenericIPAddressField(db_index=True)),
                ('nasidentifier', models.CharField(blank=True, max_length=64)),
                ('nasportid', models.CharField(blank=True, max_length=15)),
                ('nasporttype', models.CharField(blank=True, max_length=32)),
                ('acctstarttime', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('acctstoptime', models.DateTimeField(blank=True, null=True)),
                ('acctsessiontime', models.BigIntegerField(default=0)),
                ('acctauthentic', models.CharField(blank=True, max_length=32)),
                ('connectinfo_start', models.TextField(blank=True)),
                ('connectinfo_stop', models.TextField(blank=True)),
                ('acctinputoctets', models.BigIntegerField(default=0)),
                ('acctoutputoctets', models.BigIntegerField(default=0)),
                ('calledstationid', models.CharField(blank=True, max_length=50)),
                ('callingstationid', models.CharField(blank=True, max_length=50)),
                ('acctterminatecause', models.CharField(blank=True, max_length=32)),
                ('servicetype', models.CharField(blank=True, max_length=32)),
                ('framedprotocol', models.CharField(blank=True, max_length=32)),
                ('framedipaddress', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Radius Accounting',
                'db_table': 'radacct',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RadCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=64, verbose_name='PPPoE Username')),
                ('attribute', models.CharField(max_length=64, verbose_name='Attribute')),
                ('op', models.CharField(default=':=', max_length=2, verbose_name='Operator')),
                ('value', models.CharField(max_length=253, verbose_name='Value')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Radius Check',
                'db_table': 'radcheck',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RadGroupCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(db_index=True, max_length=64)),
                ('attribute', models.CharField(max_length=64)),
                ('op', models.CharField(default=':=', max_length=2)),
                ('value', models.CharField(max_length=253)),
            ],
            options={
                'verbose_name': 'Radius Group Check',
                'db_table': 'radgroupcheck',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RadGroupReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(db_index=True, max_length=64)),
                ('attribute', models.CharField(max_length=64)),
                ('op', models.CharField(default='=', max_length=2)),
                ('value', models.CharField(max_length=253)),
            ],
            options={
                'verbose_name': 'Radius Group Reply',
                'db_table': 'radgroupreply',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RadiusServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='RADIUS Server Name')),
                ('host', models.CharField(max_length=100, verbose_name='RADIUS Server Host/IP')),
                ('auth_port', models.PositiveIntegerField(default=1812, verbose_name='Auth Port')),
                ('acct_port', models.PositiveIntegerField(default=1813, verbose_name='Accounting Port')),
                ('coa_port', models.PositiveIntegerField(default=3799, verbose_name='CoA Port')),
                ('secret', apps.servers.models.EncryptedField(verbose_name='Shared Secret (Encrypted)')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'RADIUS Server',
                'db_table': 'servers_radius_servers',
            },
        ),
        migrations.CreateModel(
            name='RadReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=64)),
                ('attribute', models.CharField(max_length=64)),
                ('op', models.CharField(default='=', max_length=2)),
                ('value', models.CharField(max_length=253)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Radius Reply',
                'db_table': 'radreply',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RouterConnectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('connect_test', 'Connection Test'), ('ppp_create', 'PPPoE Secret Create'), ('ppp_enable', 'PPPoE Secret Enable'), ('ppp_disable', 'PPPoE Secret Disable'), ('ppp_delete', 'PPPoE Secret Delete'), ('ppp_disconnect', 'Disconnect Active User'), ('backup', 'Router Backup'), ('import', 'Import Clients'), ('traffic', 'Traffic Check'), ('profile_sync', 'Profile Sync')], max_length=30)),
                ('target', models.CharField(blank=True, max_length=100, verbose_name='Target (username/interface)')),
                ('is_success', models.BooleanField(default=True)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_logs', to='servers.mikrotikrouter')),
            ],
            options={
                'verbose_name': 'Router Connection Log',
                'db_table': 'servers_router_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouterBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_file', models.FileField(blank=True, null=True, upload_to='router_backups/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='File Size (bytes)')),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='servers.mikrotikrouter')),
            ],
            options={
                'verbose_name': 'Router Backup',
                'db_table': 'servers_router_backups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RadUserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=64)),
                ('groupname', models.CharField(max_length=64)),
                ('priority', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Radius User Group',
                'db_table': 'radusergroup',
                'managed': True,
                'unique_together': {('username', 'groupname')},
            },
        ),
        migrations.CreateModel(
            name='RouterPPPoEProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=100, verbose_name='Profile Name (Mikrotik-এ)')),
                ('local_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Local Address Pool')),
                ('remote_address', models.CharField(blank=True, max_length=100, verbose_name='Remote Address Pool')),
                ('rate_limit', models.CharField(blank=True, max_length=50, verbose_name='Rate Limit (e.g. 10M/10M)')),
                ('dns_server', models.CharField(blank=True, max_length=100, verbose_name='DNS Server')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Synced from Router')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='router_profiles', to='configuration.package')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pppoe_profiles', to='servers.mikrotikrouter')),
            ],
            options={
                'verbose_name': 'PPPoE Profile',
                'db_table': 'servers_pppoe_profiles',
                'unique_together': {('router', 'profile_name')},
            },
        ),
    ]
