# Generated by Django 4.2.16 on 2026-10-06 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('short_code', models.CharField(help_text='যেমন: AL, SL, CL', max_length=5, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#3B82F6', help_text='Calendar-এ color', max_length=10)),
                ('is_paid', models.BooleanField(default=True, help_text='Paid ছুটি কিনা')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Leave Category',
                'db_table': 'leave_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeaveSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('intern', 'Intern'), ('all', 'All')], default='all', max_length=15)),
                ('days_per_year', models.PositiveSmallIntegerField(default=0, help_text='প্রতি বছর কতদিন ছুটি পাবে')),
                ('carry_forward', models.BooleanField(default=False, help_text='পরের বছরে carry forward করা যাবে কিনা')),
                ('max_carry_days', models.PositiveSmallIntegerField(default=0, help_text='সর্বোচ্চ কতদিন carry forward করা যাবে')),
                ('encashable', models.BooleanField(default=False, help_text='Unused leave encash করা যাবে কিনা')),
                ('min_service_days', models.PositiveSmallIntegerField(default=0, help_text='Apply করতে ন্যূনতম কতদিন চাকরি করতে হবে')),
                ('is_active', models.BooleanField(default=True)),
                ('fiscal_year', models.CharField(default='2026-2027', help_text='অর্থবছর — যেমন: 2026-2027', max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setups', to='leave.leavecategory')),
            ],
            options={
                'verbose_name': 'Leave Setup',
                'db_table': 'leave_setups',
                'unique_together': {('category', 'employment_type', 'fiscal_year')},
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.CharField(default='2026-2027', max_length=9)),
                ('total_days', models.PositiveSmallIntegerField(default=0, help_text='মোট বরাদ্দ ছুটি')),
                ('used_days', models.PositiveSmallIntegerField(default=0, help_text='ব্যবহৃত ছুটি')),
                ('carry_forward_days', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.leavecategory')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Leave Balance',
                'db_table': 'leave_balances',
                'unique_together': {('employee', 'category', 'fiscal_year')},
            },
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_days', models.PositiveSmallIntegerField(default=1)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=12)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='leave/attachments/')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.leavecategory')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to='hr.employee')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaves_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leave Application',
                'db_table': 'leave_applications',
                'ordering': ['-applied_at'],
                'indexes': [models.Index(fields=['employee', 'status'], name='leave_appli_employe_5f5e24_idx'), models.Index(fields=['start_date', 'end_date'], name='leave_appli_start_d_424510_idx')],
            },
        ),
    ]
